# Generated by Django 2.2.16 on 2020-11-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='user',
            new_name='usuario',
        ),
    ]
