# Generated by Django 2.2.16 on 2020-11-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20201101_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='email',
        ),
    ]
